fn main() {
    // Read version from the root VERSION file (single source of truth).
    let raw_version = std::fs::read_to_string("../../VERSION")
        .expect("Failed to read VERSION file")
        .trim()
        .to_string();

    // Canonical version string: 0.0.{VERSION}  (e.g. VERSION="26.1" → "0.0.26.1")
    let version_str = format!("0.0.{raw_version}");

    // Expose to the binary so clap --version picks it up at compile time.
    println!("cargo:rustc-env=APP_VERSION={version_str}");

    // Convert to four-part Windows version quad (e.g. "0.0.26.1")
    let parts: Vec<&str> = version_str.split('.').collect();
    let major = parts.first().copied().unwrap_or("0");
    let minor = parts.get(1).copied().unwrap_or("0");
    let patch = parts.get(2).copied().unwrap_or("0");
    let build = parts.get(3).copied().unwrap_or("0");
    let win_version = format!("{major}.{minor}.{patch}.{build}");

    // Embed the application icon and version metadata into the Windows executable.
    let mut res = winres::WindowsResource::new();

    // Icon generated by `cargo run --example generate_icon`
    res.set_icon("assets/app.ico");

    // Version metadata shown in file properties
    res.set("ProductName", "LG UltraGear Dimming Fix");
    res.set(
        "FileDescription",
        "LG UltraGear display color profile manager",
    );
    res.set("CompanyName", "supermarsx");
    res.set("LegalCopyright", "Copyright (c) supermarsx. See license.md");
    res.set("OriginalFilename", "lg-ultragear-dimming-fix.exe");
    res.set("ProductVersion", &version_str);
    res.set("FileVersion", &version_str);
    res.set_version_info(
        winres::VersionInfo::PRODUCTVERSION,
        parse_version_quad(&win_version),
    );
    res.set_version_info(
        winres::VersionInfo::FILEVERSION,
        parse_version_quad(&win_version),
    );

    // Rebuild when VERSION file changes
    println!("cargo:rerun-if-changed=../../VERSION");

    res.compile().expect("Failed to compile Windows resources");
}

/// Parse a "major.minor.patch.build" string into a u64 for winres.
fn parse_version_quad(s: &str) -> u64 {
    let parts: Vec<u16> = s.split('.').filter_map(|p| p.parse().ok()).collect();
    let major = *parts.first().unwrap_or(&0) as u64;
    let minor = *parts.get(1).unwrap_or(&0) as u64;
    let patch = *parts.get(2).unwrap_or(&0) as u64;
    let build = *parts.get(3).unwrap_or(&0) as u64;
    (major << 48) | (minor << 32) | (patch << 16) | build
}
