name: lint

on:
  push:
    branches: [ main, master, '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trust PowerShell Gallery
        shell: pwsh
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -ErrorAction Stop

      - name: Run analyzer
        shell: pwsh
        run: |
          Write-Host "Using PSScriptAnalyzer version:"; (Get-Module PSScriptAnalyzer -ListAvailable | Select-Object -First 1).Version
          Invoke-ScriptAnalyzer -Path . -Recurse -EnableExit -Settings ./PSScriptAnalyzerSettings.psd1

